# Generated by Django 5.2.8 on 2025-12-19 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hodimlar', '0004_alter_hodim_id'),
        ('mahsulotlar', '0003_alter_mahsulot_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sotuv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mijoz_ismi', models.CharField(max_length=200, verbose_name='Mijoz ismi')),
                ('mijoz_telefon', models.CharField(max_length=20, verbose_name='Mijoz telefon')),
                ('miqdor', models.PositiveIntegerField(default=1, verbose_name='Sotilgan miqdor')),
                ('narx', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sotuv narxi')),
                ('holati', models.CharField(choices=[('kutilmoqda', 'Kutilmoqda'), ('tasdiqlangan', 'Tasdiqlangan'), ('yetkazilgan', 'Yetkazilgan'), ('bekor_qilingan', 'Bekor qilingan')], default='kutilmoqda', max_length=50, verbose_name='Holati')),
                ('izoh', models.TextField(blank=True, verbose_name='Izoh')),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('yangilangan_vaqt', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sotuvlar', to='mahsulotlar.mahsulot', verbose_name='Mahsulot')),
                ('sotuvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sotuvlar', to='hodimlar.hodim', verbose_name='Sotuvchi')),
            ],
            options={
                'verbose_name': 'Sotuv',
                'verbose_name_plural': 'Sotuvlar',
                'ordering': ['-yaratilgan_vaqt'],
            },
        ),
    ]
