# Generated by Django 5.2.8 on 2025-12-22 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahsulotlar', '0005_alter_mahsulot_id'),
        ('sotuv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sotuv',
            name='mahsulot',
        ),
        migrations.RemoveField(
            model_name='sotuv',
            name='miqdor',
        ),
        migrations.RemoveField(
            model_name='sotuv',
            name='narx',
        ),
        migrations.AddField(
            model_name='sotuv',
            name='jami_summa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Jami summa'),
        ),
        migrations.AlterField(
            model_name='sotuv',
            name='holati',
            field=models.CharField(choices=[('kutilmoqda', 'Kutilmoqda'), ('tasdiqlangan', 'Tasdiqlangan'), ('yetkazilgan', 'Yetkazilgan'), ('bekor_qilingan', 'Bekor qilingan')], default='tasdiqlangan', max_length=50, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='sotuv',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sotuv',
            name='mijoz_ismi',
            field=models.CharField(blank=True, default='Mijoz', max_length=200, verbose_name='Mijoz ismi'),
        ),
        migrations.AlterField(
            model_name='sotuv',
            name='mijoz_telefon',
            field=models.CharField(blank=True, max_length=20, verbose_name='Mijoz telefon'),
        ),
        migrations.CreateModel(
            name='SotuvItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.PositiveIntegerField(default=1, verbose_name='Miqdor')),
                ('narx', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sotuv narxi')),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sotuv_items', to='mahsulotlar.mahsulot', verbose_name='Mahsulot')),
                ('sotuv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sotuv.sotuv', verbose_name='Sotuv')),
            ],
            options={
                'verbose_name': 'Sotuv mahsuloti',
                'verbose_name_plural': 'Sotuv mahsulotlari',
            },
        ),
    ]
