# Generated by Django 6.0 on 2025-12-23 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahsulotlar', '0006_mahsulotvariant'),
        ('sotuv', '0002_remove_sotuv_mahsulot_remove_sotuv_miqdor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sotuvitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sotuv_items', to='mahsulotlar.mahsulotvariant', verbose_name='Variant'),
        ),
    ]
