# Generated by Django 5.2.8 on 2026-01-01 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sotuv', '0003_sotuvitem_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sotuv',
            name='holati',
        ),
        migrations.RemoveField(
            model_name='sotuvitem',
            name='variant',
        ),
    ]
