# Generated by Django 5.2.8 on 2026-01-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sotuv', '0004_remove_sotuv_holati_remove_sotuvitem_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='sotuvitem',
            name='litre',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Litr'),
        ),
    ]
