# Generated by Django 5.2.8 on 2026-01-04 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sotuv', '0005_sotuvitem_litre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sotuv',
            name='mijoz_ismi',
        ),
        migrations.RemoveField(
            model_name='sotuv',
            name='mijoz_telefon',
        ),
    ]
