# Generated by Django 5.2.8 on 2026-01-04 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sotuv', '0006_remove_sotuv_mijoz_ismi_remove_sotuv_mijoz_telefon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sotuvitem',
            name='litre',
        ),
    ]
