# Generated by Django 5.2.8 on 2025-12-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ishchilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Ism')),
                ('content', models.IntegerField(verbose_name='Yoshi')),
                ('createdat', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan_vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
            ],
            options={
                'verbose_name': 'Ishchi',
                'verbose_name_plural': 'Ishcilar',
                'ordering': ['-createdat'],
            },
        ),
    ]
