# Generated by Django 6.0 on 2025-12-19 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ishchilar',
        ),
    ]
