# Generated by Django 5.2.8 on 2025-12-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200, verbose_name='Mahsulot nomi')),
                ('tavsif', models.TextField(blank=True, verbose_name='Tavsif')),
                ('narx', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narx')),
                ('miqdor', models.IntegerField(default=0, verbose_name='Miqdor')),
                ('turi', models.CharField(choices=[('elektronika', 'Elektronika'), ('kiyim', 'Kiyim'), ('oziq_ovqat', 'Oziq-ovqat'), ('mebel', 'Mebel'), ('sport', 'Sport'), ('kitob', 'Kitob'), ('boshqa', 'Boshqa')], default='boshqa', max_length=50, verbose_name='Mahsulot turi')),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('yangilangan_vaqt', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['-yaratilgan_vaqt'],
            },
        ),
    ]
