# Generated by Django 5.2.8 on 2025-12-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahsulotlar', '0004_mahsulotturi_migrate_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahsulot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
