# Generated by Django 6.0 on 2025-12-23 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahsulotlar', '0005_alter_mahsulot_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MahsulotVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100, verbose_name='Variant nomi')),
                ('narx', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Narx')),
                ('miqdor', models.IntegerField(default=0, verbose_name='Miqdor')),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantlar', to='mahsulotlar.mahsulot', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Mahsulot varianti',
                'verbose_name_plural': 'Mahsulot variantlari',
            },
        ),
    ]
