# Generated by Django 5.2.8 on 2025-12-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahsulotlar', '0006_mahsulotvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulot',
            name='litre',
            field=models.CharField(choices=[('0.5', '0.5L'), ('1.0', '1L'), ('1.5', '1.5L'), ('2.0', '2L'), ('5.0', '5L'), ('none', 'N/A')], default='none', max_length=10, verbose_name='Litr'),
        ),
    ]
