# Generated by Django 5.2.8 on 2025-12-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahsulotlar', '0008_alter_mahsulot_litre'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulotturi',
            name='allowed_litres',
            field=models.JSONField(blank=True, default=list, verbose_name='Ruxsat etilgan litrlar'),
        ),
    ]
