# Generated by Django 5.2.8 on 2025-12-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahsulotlar', '0009_mahsulotturi_allowed_litres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahsulot',
            name='litre',
            field=models.CharField(choices=[('0.29', '0.29L'), ('0.33', '0.33L'), ('0.45', '0.45L'), ('0.5', '0.5L'), ('0.7', '0.7L'), ('1.0', '1L'), ('1.5', '1.5L'), ('2.0', '2L'), ('2.5', '2.5L'), ('5.0', '5L'), ('none', 'N/A')], default='none', max_length=10, verbose_name='Litr'),
        ),
    ]
