# Generated by Django 5.2.8 on 2026-01-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahsulotlar', '0010_alter_mahsulot_litre'),
        ('sotuv', '0004_remove_sotuv_holati_remove_sotuvitem_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mahsulot',
            name='tavsif',
        ),
        migrations.RemoveField(
            model_name='mahsulotturi',
            name='allowed_litres',
        ),
        migrations.RemoveField(
            model_name='mahsulotturi',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='mahsulotturi',
            name='tavsif',
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='litre',
            field=models.JSONField(blank=True, default=list, verbose_name='Litrlar'),
        ),
        migrations.DeleteModel(
            name='MahsulotVariant',
        ),
    ]
