# Generated by Django 5.2.8 on 2026-01-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahsulotlar', '0011_remove_mahsulot_tavsif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulot',
            name='barcode',
            field=models.CharField(blank=True, help_text='Mahsulot barcode raqami', max_length=100, null=True, unique=True, verbose_name='Barcode'),
        ),
    ]
