# Generated by Django 5.2.8 on 2026-01-04 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mahsulotlar', '0012_mahsulot_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mahsulot',
            name='litre',
        ),
    ]
