# Generated by Django 5.2.8 on 2025-12-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hodimlar', '0003_alter_hodim_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hodim',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
