# Generated by Django 5.2.8 on 2025-12-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hodimlar', '0004_alter_hodim_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hodim',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hodim',
            name='telefon',
            field=models.CharField(max_length=20, verbose_name='Telefon'),
        ),
    ]
